[package]
name = "krates"
version = "0.1.0"
authors = ["Jake Shadle <jake.shadle@embark-studios.com>"]
edition = "2018"

[dependencies]
cargo_metadata = "0.9.1"
cfg-expr = "0.1.0"
petgraph = "0.5.0"
semver = "0.9.0"

[patch.crates-io]
#cfg-expr = { path = "../" }